name: Kotlin Build Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # HAPUS BAGIAN defaults: working-directory DI SINI
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        # Ini akan mencari gradlew di folder utama (root)
        run: chmod +x gradlew

      - name: Build with Gradle
        # Ini akan menjalankan perintah dari folder utama
        run: ./gradlew assembleRelease --no-daemon --parallel
        env:
          ORG_GRADLE_PROJECT_jvmargs: -Xmx2048m -XX:MaxMetaspaceSize=512m

      - name: Upload to Firebase App Distribution
        uses: w9jds/firebase-action@master
        with:
          # Pastikan path ini sesuai dengan struktur folder Anda
          args: appdistribution:distribute app/build/outputs/apk/release/app-release.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "tester-group"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}